### PR TITLE
Apple Silicon Builds

### LINKED ISSUE #185: [request] Add apple silicon mac build
Currently the mac build targets intel macs. Could there be a build for apple silicon (e.g. M1 chip) too?

### PR DESCRIPTION
**Pull request by latter-bolden**
closes #185

Adds support for packaging Port on apple silicon. Built fine locally, but I don't have an m1 device to test it on.

@arthyn not sure if there are other places we need to update this?

### CODE REVIEW

**Comment by latter-bolden** [comment]
Changing to draft until I look into supporting this from the urbit binary side.

**Comment by arthyn** [comment]
It should actually work already from the binary's perspective. My wife has an M1 I'll try to build it and see if it works on her machine.

**Comment by latter-bolden** [comment]
Yeah, I figured it would still work with degraded performance. Looks like until we have M1 Action runners, that might be the best we can reasonably do.

**Comment by latter-bolden** [comment]
Switching this back to full PR from draft.

 If you're able to test it on M1 @arthyn , I think we can merge this. No sense in holding up the perf gains on the port side while we wait for a native urbit binary

**Review by arthyn — APPROVED** [review]
I think this all looks correct, just going to go ahead and merge this, but still need to try the build out.

**Pull request merged**
